module.exports = ['acerbic', 'acid', 'acidic', 'acrid', 'aftertaste', 'aged',
'ambrosial', 'ample', 'appealing', 'appetizing', 'aromatic', 'astringent',
'baked', 'balsamic', 'beautiful', 'bite', 'size', 'bitter', 'bland', 'blazed',
'blended', 'blunt', 'boiled', 'brackish', 'briny', 'brown', 'browned', 'burnt',
'buttered', 'caked', 'calorie', 'candied', 'caramelized', 'caustic', 'center',
'cut', 'char', 'broiled', 'cheesy', 'chilled', 'chocolate', 'chocolate',
'flavored', 'choice', 'cholesterol', 'free', 'chunked', 'cinnamon', 'classic',
'classy', 'clove', 'coated', 'cold', 'cool', 'copious', 'country', 'crafted',
'creamed', 'creamy', 'crisp', 'crunchy', 'cured', 'cutting', 'dazzling', 'deep',
'fried', 'delectable', 'delectable', 'delicious', 'delight', 'delightful',
'distinctive', 'doughy', 'dressed', 'dripping', 'drizzle', 'drizzled', 'dry',
'dulcified', 'dull', 'edible', 'elastic', 'encrusted', 'epicurean', 'taste',
'ethnic', 'extraordinary', 'famous', 'fantastic', 'fetid', 'fiery', 'filet',
'fizzy', 'flaky', 'flat', 'flavored', 'flavorful', 'flavorless', 'flavorsome',
'fleshy', 'fluffy', 'fragile', 'free', 'free', 'range', 'fresh', 'fried',
'frosty', 'frozen', 'fruity', 'full', 'full', 'bodied', 'furry', 'famy',
'garlic', 'garlicky', 'generous', 'generous', 'portion', 'gingery', 'glazed',
'golden', 'gorgeous', 'gourmet', 'greasy', 'grilled', 'gritty', 'gustatory',
'half', 'harsh', 'heady', 'heaping', 'heart', 'healthy', 'heart', 'smart',
'hearty', 'heavenly', 'homemade', 'honey', 'honeyed', 'honey', 'glazed', 'hot',
'ice', 'cold', 'icy', 'incisive', 'indulgent', 'infused', 'insipid', 'intense',
'intriguing', 'juicy', 'jumbo', 'kosher', 'large', 'lavish', 'layered', 'lean',
'leathery', 'lemon', 'less', 'light', 'lite', 'lightly', 'salted', 'lightly',
'breaded', 'lip', 'smacking', 'lively', 'low', 'low', 'sodium', 'low', 'fat',
'lukewarm', 'luscious', 'lush', 'marinated', 'mashed', 'mellow', 'mild',
'minty', 'mixed', 'mixture', 'of', 'moist', 'moist', 'mouth', 'watering',
'nationally', 'famous', 'natural', 'nectarous', 'non', 'fat', 'nutmeg',
'nutty', 'oily', 'open', 'face', 'organic', 'overpowering', 'palatable',
'indicates', 'penetrating', 'peppery', 'perfection', 'petite', 'pickled',
'piquant', 'plain', 'pleasant', 'plump', 'poached', 'popular', 'pounded',
'prepared', 'prickly', 'pulpy', 'pungent', 'pureed', 'rancid', 'rank', 'reduced',
'refresh', 'rich', 'ripe', 'roasted', 'robust', 'rotten', 'rubbery', 'saccharine',
'saline', 'salty', 'savory', 'Sapid', 'saporific', 'saporous', 'satin', 'satiny',
'sauteed', 'savorless', 'savory', 'scrumptious', 'sea', 'salt', 'seared',
'seasoned', 'served', 'in', 'served', 'with', 'sharp', 'sharp', 'tasting',
'silky', 'simmered', 'sizzling', 'skillfully', 'small', 'smelly', 'smoked',
'smoky', 'smooth', 'smothered', 'soothing', 'sour', 'Southern', 'style',
'special', 'spiced', 'spicy', 'spiral', 'cut', 'spongy', 'sprinkled', 'stale',
'steamed', 'steamy', 'sticky', 'stinging', 'strawberry', 'flavored', 'strong',
'stuffed', 'succulent', 'sugar', 'coated', 'sugar', 'free', 'sugared', 'sugarless',
'sugary', 'superb', 'sweet', 'sweet', 'and', 'sour', 'sweetened', 'syrupy', 'tangy',
'tantalizing', 'tart', 'tasteful', 'tasteless', 'tasty', 'tender', 'tepid',
'terrific', 'thick', 'thin', 'toasted', 'toothsome', 'topped', 'tossed', 'tough',
'traditional', 'treacly', 'treat', 'unflavored', 'unsavory', 'unseasoned', 'vanilla',
'vanilla', 'flavored', 'velvety', 'vinegary', 'warm', 'waxy', 'weak', 'whipped',
'whole', 'wonderful', 'yucky', 'yummy', 'zesty', 'zingy'];
